spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8001
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: org.haoge.cloud.entities
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    # 开启驼峰命名
spring:
  profiles: dev    # 开发环境
  application:
    name: product-config   # 服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_db01?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 150    # 等待连接获取的最大超时时间
       
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
---
server:
  port: 8001
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: org.haoge.cloud.entities
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    # 开启驼峰命名
spring:
  profiles: prod    # 生产环境
  application:
    name: product-config   # 服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_db02?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5             # 数据库连接池的最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 150    # 等待连接获取的最大超时时间
       
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  